### PR TITLE
Add support for multiple template engines

### PR DESCRIPTION
**Pull request by federicobond**
Any feedback is appreciated. There is a bit of callback nesting in the `send` function. I can use promises instead if you prefer.

### CODE REVIEW

**Comment by secretfader** [comment]
I just cleaned this up a bit. I'm merging now.

**Comment by secretfader** [comment]
@federicobond Okay, I did a bit of refactoring to clean up the API. It needed doing, and this pull request seemed like a good time to handle these tasks as well.

Everything is now merged, and published to npm as v1.1.1. Thanks!

**Comment by federicobond** [comment]
@nicholaswyoung thanks for the quick response!

**Comment by secretfader** [comment]
@federicobond You're quite welcome. Thanks for using the project, and for the excellent pull request. :)

**Pull request closed without merging**
